spring.application.name=minicore


spring.datasource.url=jdbc:postgresql://localhost:5432/GestionLab
spring.datasource.username=postgres
spring.datasource.password=toor
spring.datasource.driver-class-name=org.postgresql.Driver


# Hibernate

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE

server.port=${PORT:5003}

# Keycloak OAuth2 Client Configuration
spring.security.oauth2.client.registration.keycloak.client-id=spring-lab
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/Vet_auth_demo

# Keycloak OAuth2 Resource Server Configuration (para validar JWT en API REST)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/Vet_auth_demo

#Logout
spring.security.oauth2.client.provider.keycloak.end-session-endpoint=http://localhost:8080/realms/Vet_auth_demo/protocol/openid-connect/logout

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=TRACE